version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "7724:80"
    environment:
      PMA_HOST: mysqlCon
    volumes:
      - /root/config.inc.php:/etc/phpmyadmin/config.inc.php:ro