"""update meta

Revision ID: 58d9b99ed5d6
Revises: 
Create Date: 2024-03-23 04:11:39.887348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '58d9b99ed5d6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file', sa.Column('public', sa.BOOLEAN(), nullable=True))
    op.alter_column('file', 'name',
               existing_type=mysql.VARCHAR(length=128),
               type_=sa.String(length=256, collation='utf8mb4_general_ci'),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('file', 'name',
               existing_type=sa.String(length=256, collation='utf8mb4_general_ci'),
               type_=mysql.VARCHAR(length=128),
               existing_nullable=True)
    op.drop_column('file', 'public')
    # ### end Alembic commands ###
