"""update meta

Revision ID: 8fb9230ee6a8
Revises: 
Create Date: 2024-03-23 00:28:29.723740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8fb9230ee6a8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albumsMeta', sa.Column('name', sa.String(length=128), nullable=True))
    op.alter_column('user', 'avatar_id',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('user', 'base_album',
               existing_type=mysql.VARCHAR(length=15),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'base_album',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
    op.alter_column('user', 'avatar_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=15),
               existing_nullable=True)
    op.drop_column('albumsMeta', 'name')
    # ### end Alembic commands ###
